services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: preetam@123P
      MYSQL_DATABASE: ecoride
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysql", "-u", "root", "-ppreetam@123P", "-e", "SELECT 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s

  backend:
    image: ecoride-backend
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:mysql://mysql:3306/ecoride?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: preetam@123P
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    image: ecoride-frontend
    ports:
      - "3001:3000"
    depends_on:
      - backend